Include /opt/coraza-nginx/current/conf/coraza.conf
Include /opt/coraza-nginx/current/conf/config.d/*.conf
Include /opt/coraza-nginx/current/conf/crs-setup.conf
Include /opt/coraza-nginx/current/share/coraza/crs/plugins/*-config.conf
Include /opt/coraza-nginx/current/share/coraza/crs/plugins/*-before.conf
Include /opt/coraza-nginx/current/share/coraza/crs/rules/*.conf
Include /opt/coraza-nginx/current/share/coraza/crs/plugins/*-after.conf
Include /opt/coraza-nginx/current/conf/overrides/*.conf
